# Generated by Django 4.2.1 on 2024-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_order_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='./media/obezyana.jpg/', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_add',
            field=models.DateField(),
        ),
    ]
